name: Update slices

on:
  workflow_dispatch:
    inputs:
      commit-updates:
        description: Push updated slices
        required: false
        default: true
        type: boolean
      commit-msg:
        description: Optional commit message
        required: false
        default: "Slice update"
        type: string
      args:
        description: Generate only this slice type
        required: false
        type: string
      filter:
        description: Generate only for these languages (separated by spaces)
        required: false
        default: 'java javascript python'
        type: string
      reset-cache:
        description: Don't use the cached versions of the sample repos
        required: false
        type: boolean
        default: false
      debug-cmds:
        description: Don't execute commands, just print and output shell files
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm install -g @appthreat/atom

      -  name: sdkman install
         run: |
           curl -s "https://get.sdkman.io" | bash
           source "/home/runner/.sdkman/bin/sdkman-init.sh"
           echo sdkman_auto_answer=true > ~/.sdkman/etc/config

      - name: Restore sample repo cache
        if: ${{ ! inputs.reset-cache }}
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: /home/runner/work/src_repos
          key: ${{ runner.os }}-atom-samples

      - name: Restore sdkman install cache
        if: ${{ ! inputs.reset-cache }}
        uses: actions/cache/restore@v3
        id: sdkman-cache
        with:
          path: /home/runner/.sdkman/candidates
          key: ${{ runner.os }}-sdkman

      - name: Generate slices
        if: ${{ ! inputs.debug-cmds }}
        env:
          SDKMAN_DIR: /home/runner/.sdkman
        run: |
           python generate.py --skip-clone -s ${{ inputs.filter-slice-type }} -i ${{ inputs.filter }}
           bash /home/runner/work/atom-samples/atom-samples/sdkman_installs.sh
           bash /home/runner/work/atom-samples/atom-samples/atom_commands.sh

      - name: Upload slices as artifact
        uses: actions/upload-artifact@v3
        with:
          name: slices
          path: /home/runner/work/atom-samples/atom-samples/**/*.json

      - name: Upload shell scripts generated as artifact
        uses: actions/upload-artifact@v3
        with:
          name: scripts
          path: /home/runner/work/atom-samples/atom-samples/*.sh

      - name: Save repo cache
        if: inputs.reset-cache || ${{ ! steps.cache.outputs.cache-hit }}
        uses: actions/cache/save@v3
        with:
          path: /home/runner/work/src_repos
          key: ${{ runner.os }}-atom-samples

      - name: Save sdkman cache
        if: inputs.reset-cache || ${{ ! steps.cache.outputs.cache-hit }}
        uses: actions/cache/save@v3
        with:
          path: /home/runner/.sdkman/candidates
          key: ${{ runner.os }}-sdkman

      - name: Commit changes
        if: inputs.commit-updates && ${{ ! inputs.debug-cmds }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Caroline Russell"
          git config user.email "caroline@appthreat.dev"
          git add .
          git commit -m "${{ inputs.commit-msg }}"
          git push
