name: Update slices

on:
  workflow_dispatch:
    inputs:
      commit-updates:
        description: Push updated slices
        required: false
        default: true
        type: boolean
      commit-msg:
        description: Optional commit message
        required: false
        default: "Slice update"
        type: string
      args:
        description: Generate only this slice type
        required: false
        type: string
      filter:
        description: Generate only for these languages (separated by spaces)
        required: false
        default: 'java javascript python'
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm install -g @appthreat/atom

      - name: Update slices
        run: |
          sudo python ./generate.py -s ${{ inputs.filter-slice-type }} -i ${{ inputs.filter }}

      - name: Upload slices as artifact
        uses: actions/upload-artifact@v3
        with:
          name: slices
          path: /home/runner/work/atom-samples/atom-samples/**/*.json

      - name: Upload shell scripts generated as artifact
        uses: actions/upload-artifact@v3
        with:
          name: scripts
          path: /home/runner/work/atom-samples/atom-samples/*.sh

      - name: Commit changes
        if: inputs.commit-updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm /home/runner/work/atom-samples/atom-samples/atom_commands.sh
          rm /home/runner/work/atom-samples/atom-samples/sdkman_installs.sh
          git config user.name "Caroline Russell"
          git config user.email "caroline@appthreat.dev"
          git add .
          git commit -m "${{ inputs.commit-msg }}"
          git push
